name: all_about_maps
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  geocoding: ^2.1.1
  geolocator: ^11.0.0
  uuid: ^4.3.3
  location: ^5.0.3
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true